spring:
  h2:
    console:
      enabled: true
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:./data/testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  # 로그 레벨 설정
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


#swagger
springdoc:
  version: v1.0.0
  swagger-ui:
  packages-to-scan: com.example.cms